In [188]:
import numpy as np
import pandas as pd

In [189]:
df = pd.read_csv('data/customer.csv').drop(columns=['age','gender'])

In [190]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


### 1. Ordinal Encoding

In [191]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [192]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [193]:
X_train

,review,education
23,Good,School
21,Average,PG
33,Good,PG
18,Good,School
49,Good,UG
43,Poor,PG
14,Poor,PG
20,Average,School
6,Good,School
35,Poor,School


In [194]:
# specify order
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [195]:
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)

In [196]:
X_train

array([[2., 0.],
       [1., 2.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 0.]])

In [197]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [198]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [199]:
oe.n_features_in_

2

In [200]:
oe.inverse_transform(np.array([0,2]).reshape(1,2))

array([['Poor', 'PG']], dtype=object)

In [201]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

In [202]:
oe = OrdinalEncoder(
    categories=[
        ['Poor','Average','Good'],
        ['School','UG','PG']
    ],
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

In [203]:
# set unknown value
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']],
                    handle_unknown='use_encoded_value',
                    unknown_value=-1)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)
X_train = oe.fit_transform(X_train)
oe.transform(np.array(['Poor','college']).reshape(1,2))

d:\FEATURE_ENGINEERING_AND_SKLEARN_PIPELINE\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[ 0., -1.]])

In [204]:
# handling infrequent categories
X = np.array([['dog'] * 5 + ['cat'] * 20 + ['rabbit'] * 10 +['snake'] * 3 + ['horse'] * 2], dtype=object).T
X

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

In [205]:
enc = OrdinalEncoder(max_categories=3).fit(X)

In [206]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [207]:
enc.transform(np.array([['cat','rabbit','snake','dog']]).reshape(4,1))

array([[0.],
       [1.],
       [2.],
       [2.]])

In [208]:
enc = OrdinalEncoder(min_frequency=4).fit(X)
enc.infrequent_categories_

[array(['horse', 'snake'], dtype=object)]

In [209]:
enc.transform(np.array([['cat','rabbit','snake','dog','horse']]).reshape(5,1))

array([[0.],
       [2.],
       [3.],
       [1.],
       [3.]])

In [210]:
# update sklearn if the above command doesn't work
!pip install --upgrade scikit-learn==1.3.2

In [211]:
# handling missing data

# Example categorical data with missing values
data = [['Cat'], [np.nan], ['Dog'], ['Fish'], [np.nan]]

# Setting encoded_missing_value to -1, indicating we want missing values to be encoded as -1
encoder = OrdinalEncoder(encoded_missing_value=-1)

encoded_data = encoder.fit_transform(data)

print(encoded_data)

[[ 0.]
 [-1.]
 [ 1.]
 [ 2.]
 [-1.]]


### LabelEncoder

In [212]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [213]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [214]:
from sklearn.preprocessing import LabelEncoder

In [215]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [216]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [217]:
le.inverse_transform(np.array([1,1,0]))

array(['Yes', 'Yes', 'No'], dtype=object)

### 2. OneHotEncoder

In [218]:
cars = pd.read_csv('data/cars.csv')
cars.head()

,brand,km_driven,fuel,owner,selling_price
0,Maruti,145500,Diesel,First Owner,450000
1,Skoda,120000,Diesel,Second Owner,370000
2,Honda,140000,Petrol,Third Owner,158000
3,Hyundai,127000,Diesel,First Owner,225000
4,Maruti,120000,Petrol,First Owner,130000


In [219]:
cars.isnull().sum()

brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

In [220]:
X = cars.iloc[:,0:4]
y = cars.iloc[:,-1]

In [221]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [222]:
X_train['fuel'].nunique()

4

In [223]:
from sklearn.preprocessing import OneHotEncoder

In [224]:
ohe = OneHotEncoder(sparse_output=False, dtype=np.int32)

In [225]:
ohe.fit_transform(X_train)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], shape=(6502, 830), dtype=int32)

In [226]:
X_train = ohe.fit_transform(X_train)
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], shape=(6502, 830), dtype=int32)

In [227]:
X_train.shape

(6502, 830)

In [228]:
ohe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'], dtype=object),
 array([      1,    1000,    1303,    1500,    1600,    1620,    2000,
           2136,    2286,    2300,    2350,    2560,    2600,    2700,
           2789,    2860,    3000,    3010,    3100,    3177,    3500,
           3564,    4000,    4295,    4300,    4500,    4701,    4875,
           5000,    5400,    5500,    5621,    5800,    6000,    6001,
           6200,    6500,    6544,    6550,    6750,    6757,    6825,
           7000,    7032,    7200,    7400,    7500,    7600,    7672,
           7720,    7800,    7976,    8000,    8079,    8500,    8576,
           9000,    9200,    9500,    9558,    9599,

In [229]:
ohe.feature_names_in_

array(['brand', 'km_driven', 'fuel', 'owner'], dtype=object)

In [230]:
ohe.n_features_in_

4

In [231]:
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia',
       'brand_Land', 'brand_Lexus', 'brand_MG', 'brand_Mahindra',
       'brand_Maruti', 'brand_Mercedes-Benz', 'brand_Mitsubishi',
       'brand_Nissan', 'brand_Opel', 'brand_Peugeot', 'brand_Renault',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'km_driven_1', 'km_driven_1000', 'km_driven_1303',
       'km_driven_1500', 'km_driven_1600', 'km_driven_1620',
       'km_driven_2000', 'km_driven_2136', 'km_driven_2286',
       'km_driven_2300', 'km_driven_2350', 'km_driven_2560',
       'km_driven_2600', 'km_driven_2700', 'km_driven_2789',
       'km_driven_2860', 'km_driven_3000', 'km_driven_3010',
       'km_driven_3100', 'km_driven_3177', 'km_driven_3500',
       'km_d

In [232]:
pd.DataFrame(ohe.fit_transform(X_train),columns=ohe.get_feature_names_out())

,x0_0,x0_1,x1_0,x1_1,x2_0,x2_1,x3_0,x3_1,x4_0,x4_1,...,x825_0,x825_1,x826_0,x826_1,x827_0,x827_1,x828_0,x828_1,x829_0,x829_1
0,1,0,1,0,1,0,1,0,1,0,...,0,1,1,0,1,0,1,0,1,0
1,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,0,1,1,0,1,0
2,1,0,1,0,1,0,1,0,1,0,...,1,0,0,1,1,0,1,0,1,0
3,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,0,1,1,0,1,0
4,1,0,1,0,1,0,1,0,1,0,...,0,1,1,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6497,1,0,1,0,1,0,1,0,1,0,...,0,1,1,0,1,0,1,0,1,0
6498,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,0,1,1,0,1,0
6499,1,0,1,0,1,0,1,0,1,0,...,0,1,1,0,1,0,1,0,1,0
6500,1,0,1,0,1,0,1,0,1,0,...,0,1,1,0,1,0,1,0,1,0


In [233]:
# form dataframe again if required

In [234]:
# show sparse_array false

In [235]:
# show dtype

In [236]:
# drop
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

ohe = OneHotEncoder(drop='first',sparse_output=False)
ohe.fit_transform(X_train).shape

(6502, 826)

In [237]:
ohe.drop_idx_

array([0, 0, 0, 0], dtype=object)

In [238]:
# handling rare categories
X_train['brand'].value_counts()

brand
Maruti           1953
Hyundai          1127
Mahindra          635
Tata              586
Toyota            391
Honda             369
Ford              320
Chevrolet         185
Renault           183
Volkswagen        154
BMW                96
Skoda              82
Nissan             62
Jaguar             59
Volvo              54
Datsun             48
Mercedes-Benz      43
Fiat               35
Audi               30
Jeep               26
Lexus              22
Mitsubishi         13
Force               6
Land                5
Kia                 4
Ambassador          3
MG                  3
Daewoo              3
Isuzu               2
Ashok               1
Peugeot             1
Opel                1
Name: count, dtype: int64

In [239]:
cars['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [240]:
# using min frequency

ohe = OneHotEncoder(sparse_output=False, min_frequency=100)
ohe.fit_transform(X_train).shape

(6502, 35)

In [241]:
ohe.get_feature_names_out()

array(['brand_Chevrolet', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Mahindra', 'brand_Maruti', 'brand_Renault', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'km_driven_10000', 'km_driven_15000', 'km_driven_20000',
       'km_driven_25000', 'km_driven_30000', 'km_driven_35000',
       'km_driven_40000', 'km_driven_50000', 'km_driven_60000',
       'km_driven_70000', 'km_driven_80000', 'km_driven_90000',
       'km_driven_100000', 'km_driven_110000', 'km_driven_120000',
       'km_driven_infrequent_sklearn', 'fuel_Diesel', 'fuel_Petrol',
       'fuel_infrequent_sklearn', 'owner_First Owner',
       'owner_Fourth & Above Owner', 'owner_Second Owner',
       'owner_Third Owner', 'owner_infrequent_sklearn'], dtype=object)

In [242]:
# using max_categories
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', max_categories=15)
ohe.fit_transform(X_train).shape

(6502, 39)

In [243]:
ohe.get_feature_names_out()

array(['brand_BMW', 'brand_Chevrolet', 'brand_Ford', 'brand_Honda',
       'brand_Hyundai', 'brand_Jaguar', 'brand_Mahindra', 'brand_Maruti',
       'brand_Nissan', 'brand_Renault', 'brand_Skoda', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'km_driven_15000', 'km_driven_20000', 'km_driven_25000',
       'km_driven_30000', 'km_driven_35000', 'km_driven_40000',
       'km_driven_50000', 'km_driven_60000', 'km_driven_70000',
       'km_driven_80000', 'km_driven_90000', 'km_driven_100000',
       'km_driven_110000', 'km_driven_120000',
       'km_driven_infrequent_sklearn', 'fuel_CNG', 'fuel_Diesel',
       'fuel_LPG', 'fuel_Petrol', 'owner_First Owner',
       'owner_Fourth & Above Owner', 'owner_Second Owner',
       'owner_Test Drive Car', 'owner_Third Owner'], dtype=object)

In [244]:
# how to handle unknown category
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

ohe = OneHotEncoder(drop='first',sparse_output=False)
ohe.fit_transform(X_train)

ohe.transform(np.array(['local','Petrol']).reshape(1,2))

d:\FEATURE_ENGINEERING_AND_SKLEARN_PIPELINE\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


ValueError: X has 2 features, but OneHotEncoder is expecting 4 features as input.

In [ ]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe.fit_transform(X_train)

ohe.transform(np.array(['local','Petrol']).reshape(1,2))

In [ ]:
ohe.inverse_transform(np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]).reshape(1,36))

### LabelBinarizer

In [ ]:
from sklearn.preprocessing import LabelBinarizer

# Sample target variable for a multi-class classification problem
y = ['cat', 'dog', 'fish', 'dog', 'cat']

# Initialize the LabelBinarizer
lb = LabelBinarizer()

# Fit and transform the target variable
y_binarized = lb.fit_transform(y)

print("Binarized labels:\n", y_binarized)

# Inverse transform to recover original labels
y_original = lb.inverse_transform(y_binarized)

print("Original labels:\n", y_original)


In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

# Example multi-label data
y = [('red', 'blue'), ('blue', 'green'), ('green',), ('red',)]

# Initialize MultiLabelBinarizer
mlb = MultiLabelBinarizer()

# Fit and transform the data to binary matrix format
Y = mlb.fit_transform(y)

print("Binary matrix:\n", Y)
print("Class labels:", mlb.classes_)

# Inverse transform to recover original labels
y_inv = mlb.inverse_transform(Y)
print("Inverse transformed labels:", y_inv)


### 3. Count Encoder/Frequency Encoder

In [ ]:
!pip install category_encoders

In [ ]:
# dataset generation
import pandas as pd
import numpy as np
import category_encoders as ce

# Simulating a dataset
data = {
    'Age': np.random.randint(20, 60, size=100).astype(float),  # Random ages between 20 and 60
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana'], size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG'], size=100),
    'Package': np.random.rand(100) * 100  # Random package values for demonstration
}

# Introducing missing values in 'Age' column (5%)
np.random.seed(0)  # For reproducibility
missing_indices = np.random.choice(data['Age'].shape[0], replace=False, size=int(data['Age'].shape[0] * 0.05))
data['Age'][missing_indices] = np.nan

df = pd.DataFrame(data)

df.head()

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Package']), df['Package'], test_size=0.2, random_state=42)

In [ ]:
X_train.head()

In [ ]:
X_train['State'].value_counts()

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
import sklearn

In [ ]:
class CountEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, columns=None):
        self.columns = columns
        self.count_map = {}

    def fit(self, X, y=None):
        if self.columns is None:
            self.columns = X.columns
        for col in self.columns:
            self.count_map[col] = X[col].value_counts().to_dict()
        return self

    def transform(self, X):
        X = X.copy()
        for col in self.columns:
            X[col] = X[col].map(self.count_map[col]).fillna(0)
        return X

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('age_missing', SimpleImputer(strategy='mean'), ['Age']),
        ('cat_state', CountEncoder(), ['State']),
        ('education_ordinal', OrdinalEncoder(), ['Education'])
    ])

sklearn.set_config(transform_output="pandas")

In [ ]:
preprocessor.fit_transform(X_train)

In [ ]:
# using category encoders
from category_encoders.count import CountEncoder

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('age_missing', SimpleImputer(strategy='mean'), ['Age']),
        ('cat_state', CountEncoder(normalize=True), ['State']),
        ('education_ordinal', OrdinalEncoder(), ['Education'])
    ])
sklearn.set_config(transform_output="pandas")

In [ ]:
preprocessor.fit_transform(X_train)

In [ ]:
# frequency encoding

In [ ]:
# parameters
import pandas as pd
import numpy as np
import category_encoders as ce

# Simulating a dataset
np.random.seed(42)  # For reproducibility
data = {
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana', np.NaN], size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG', np.NaN], size=100)
}
df = pd.DataFrame(data)

df.head(25)


In [ ]:
df.isnull().sum()

In [ ]:
# Initialize the CountEncoder with various parameters
encoder = ce.CountEncoder(
    cols=['State', 'Education'],  # Specify columns to encode. None would automatically select categorical columns.
    handle_missing='error',  # Treat NaNs as a countable category
    handle_unknown='error',  # Treat unknown categories as NaNs (if seen during transform but not in fit)
)

In [ ]:
# Fit and transform the dataset
encoder.fit_transform(df)

#print(encoded_df.head(25))

In [ ]:
encoder.mapping

In [ ]:
new_data = pd.DataFrame({'State': ['Bihar'], 'Education': ['UG']})

encoder.transform(new_data)

In [ ]:
np.random.seed(0)  # For reproducibility
data = {
    'Category': np.random.choice(['A', 'B', 'C', 'D', 'E', 'F', np.nan], size=100, p=[0.3, 0.25, 0.15, 0.15, 0.05, 0.05, 0.05]),
    'Value': np.random.rand(100)
}

df = pd.DataFrame(data)

df.sample(10)


In [ ]:
df['Category'].value_counts()

In [ ]:
encoder = ce.CountEncoder(
    cols=['Category'],
    min_group_size=10,  # Groups with counts less than 5 will be combined
    min_group_name='salman',  # Use default naming for combined minimum groups
)

# Fit and transform the dataset
encoded_df = encoder.fit_transform(df['Category'])

# Display the original and encoded data for comparison
df['Encoded'] = encoded_df
print(df.head(20))

In [ ]:
encoder.mapping

### Binary Encoder

In [ ]:
import pandas as pd
import category_encoders as ce

# Sample dataset
data = {
    'Item': ['Item1', 'Item2', 'Item3', 'Item4', 'Item5', 'Item6', 'Item7', 'Item8'],
    'Fruit': ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry', 'Fig', 'Grape', 'Honeydew']
}
df = pd.DataFrame(data)

df


In [ ]:
# Initialize the Binary Encoder
encoder = ce.BinaryEncoder(cols=['Fruit'], return_df=True)

# Fit and transform the data
df_encoded = encoder.fit_transform(df)

# Display the original and encoded data
print(df_encoded)

### Target Encoder

In [ ]:
# using category_encoder

import pandas as pd
import category_encoders as ce

# Sample data
data = {
    'Feature': ['A', 'B', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Target': [1, 0, 0, 1, 1, 1, 0, 1]
}
df = pd.DataFrame(data)

# Separating the feature and target columns
X = df.drop('Target', axis=1)
y = df['Target']

# Initialize the TargetEncoder
encoder = ce.TargetEncoder(cols=['Feature'])

# Fit the encoder using the feature data and target variable
encoder.fit(X, y)

# Transform the data
encoded = encoder.transform(X)

# Show the original and encoded data
print(pd.concat([df, encoded], axis=1))


In [ ]:
encoder.mapping

In [ ]:
!pip install --upgrade scikit-learn==1.4.0

In [ ]:
# using sklearn
import pandas as pd
from sklearn.preprocessing import TargetEncoder

# Sample data
data = {
    'Feature': ['A', 'B', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Target': [1, 0, 0, 1, 1, 1, 0, 1]
}
df = pd.DataFrame(data)

# Separating the feature and target columns
X = df.drop('Target', axis=1)
y = df['Target']

# Initialize the TargetEncoder
encoder = TargetEncoder(smooth=0.0)

# Fit the encoder using the feature data and target variable
encoder.fit(X, y)

# Transform the data
encoded = encoder.transform(X)

encoded


### Weight of Evidence

In [ ]:
!pip install category_encoders

In [ ]:
import pandas as pd
import category_encoders as ce

# Example dataset
data = {
    'Feature': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'C'],
    'Target': [1, 0, 0, 1, 1, 0, 1, 0, 1, 0]
}
df = pd.DataFrame(data)

# Define the features and target
X = df[['Feature']]
y = df['Target']

# Initialize and fit the TargetEncoder
encoder = ce.WOEEncoder(cols=['Feature'])
X_encoded = encoder.fit_transform(X, y)

# Display the original and encoded data
df['Feature_Encoded'] = X_encoded
print(df)
